name: MKTFY Web App

on:
    push:
        branches:
            - "dev"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [15.x]

        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - run: npm run build
              env:
                  CI: false
                  REACT_APP_DOMAIN: ${{secrets.REACT_APP_DOMAIN}}
                  REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
                  REACT_APP_REALM: ${{secrets.REACT_APP_REALM}}
                  REACT_APP_AUDIENCE: ${{secrets.REACT_APP_AUDIENCE}}
                  REACT_APP_ENV: ${{secrets.REACT_APP_ENV}}
            # - run: npm test
            - uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
                  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  AWS_REGION: "ca-central-1"
                  SOURCE_DIR: "build"
